name: test_flutter
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  get: 4.6.6
  another_flutter_splash_screen: 1.2.1
  introduction_screen: 3.1.14
  lottie: 3.1.2
  flutter_launcher_icons: 0.13.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: 4.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon-apps.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  assets:
    - assets/iconsplash.png
    - assets/first-introduction.json
    - assets/second-introduction.json
    - assets/login-page.json
    - assets/register-page.json
  uses-material-design: true
